# Generated by Django 4.0.5 on 2022-06-21 15:02

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartCrawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='建立日期')),
            ],
        ),
        migrations.AddField(
            model_name='markingdepartment',
            name='create_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='markingdepartment',
            name='update_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='markingdepartmentdependsbuildings',
            name='create_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='markingdepartmentdependsbuildings',
            name='update_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='markingdepartmentdependslocationnumber',
            name='create_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='markingdepartmentdependslocationnumber',
            name='update_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='markingdepartmentpublicpart',
            name='create_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='markingdepartmentpublicpart',
            name='update_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='othershipdepartment',
            name='create_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='othershipdepartment',
            name='update_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='ownershipdepartment',
            name='create_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='建立日期'),
        ),
        migrations.AddField(
            model_name='ownershipdepartment',
            name='update_time',
            field=backend.models.DateTimeWithoutTZField(default=datetime.datetime.now, verbose_name='更新日期'),
        ),
    ]
