# Generated by Django 4.0.5 on 2022-06-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_startcrawler_markingdepartment_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startcrawler',
            options={'verbose_name': '爬蟲紀錄', 'verbose_name_plural': '爬蟲紀錄'},
        ),
        migrations.AddField(
            model_name='startcrawler',
            name='status',
            field=models.BooleanField(default=False, verbose_name='狀態'),
        ),
    ]
